inherit_from: .rubocop_todo.yml
# 自動生成されたファイルを対象外にする
AllCops:
  Exclude:
    - "Gemfile"
    - "node_modules/**/*"
    - "bin/*"
    - "db/**/*"
    - "config/**/*"
    - "test/**/*"
    - "spec/**/*"

# 以下を追記
Style/FrozenStringLiteralComment:
  Enabled: false

  # 1行の最大文字数を150字にする
LineLength:
  Max: 150

  # ドキュメントのないclass, moduleを許可する
Style/Documentation:
  Enabled: false

  # rubocopをかけたときに警告が出たのでtrue or falseの選択
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
