version: 2.1

jobs:
  rspec:
   steps:
      - run:
         name: update bundler
         command: |
           gem update --system
           gem install bundler:2.4.7

      - run:
         name: yarn Install
         command: yarn install
      - run: bundle exec bin/webpack


      - run:
          name: RSpec
          command: bundle exec rspec
