version: 2.1
jobs:
  rspec:
    docker:
      - image: ruby:3.0.3
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          # DB_PASSWORD: password
      - image: circleci/mysql:5.6
        environment:
          - MYSQL_ROOT_PASSWORD: rootpw
          - MYSQL_DATABASE: fitness_app01_test
          - MYSQL_USER: root
          # - MYSQL_ROOT_PASSWORD: password
    working_directory: ~/fitness_app01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: update bundler
          command: |
            gem update --system
            gem install bundler:2.4.7
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run: bundle exec rails db:create RAILS_ENV=test
      - run: bundle exec rails db:schema:load RAILS_ENV=test
      - run: bundle exec bin/webpack
      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  version: 2.1
  rspec_and_rubocop_workflow:
    jobs:
      - rspec