# MySQL. Versions 8.0.32 and up are supported.

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user # development.envで記載したユーザ名
  password: <%= ENV["MYSQL_PASSWORD"] %>
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: e_note_development

test:
  <<: *default
  username: test_user
  password: passw0rd
  database: docker_test
  host: test-db

production:
  <<: *default
  database: e_note_production
  username: <%= Rails.application.credentials.db[:user_name] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:endpoint] %>
  pool: 20
  timeout: 1000